/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StravaRouteImport } from './routes/strava'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GithubRouteImport } from './routes/github'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStravaCallbackRouteImport } from './routes/api.strava.callback'
import { Route as ApiStravaAuthRouteImport } from './routes/api.strava.auth'

const StravaRoute = StravaRouteImport.update({
  id: '/strava',
  path: '/strava',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaCallbackRoute = ApiStravaCallbackRouteImport.update({
  id: '/api/strava/callback',
  path: '/api/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaAuthRoute = ApiStravaAuthRouteImport.update({
  id: '/api/strava/auth',
  path: '/api/strava/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/github': typeof GithubRoute
  '/home': typeof HomeRoute
  '/strava': typeof StravaRoute
  '/api/strava/auth': typeof ApiStravaAuthRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/github': typeof GithubRoute
  '/home': typeof HomeRoute
  '/strava': typeof StravaRoute
  '/api/strava/auth': typeof ApiStravaAuthRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/github': typeof GithubRoute
  '/home': typeof HomeRoute
  '/strava': typeof StravaRoute
  '/api/strava/auth': typeof ApiStravaAuthRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/github'
    | '/home'
    | '/strava'
    | '/api/strava/auth'
    | '/api/strava/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/github'
    | '/home'
    | '/strava'
    | '/api/strava/auth'
    | '/api/strava/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/github'
    | '/home'
    | '/strava'
    | '/api/strava/auth'
    | '/api/strava/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GithubRoute: typeof GithubRoute
  HomeRoute: typeof HomeRoute
  StravaRoute: typeof StravaRoute
  ApiStravaAuthRoute: typeof ApiStravaAuthRoute
  ApiStravaCallbackRoute: typeof ApiStravaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strava': {
      id: '/strava'
      path: '/strava'
      fullPath: '/strava'
      preLoaderRoute: typeof StravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/callback': {
      id: '/api/strava/callback'
      path: '/api/strava/callback'
      fullPath: '/api/strava/callback'
      preLoaderRoute: typeof ApiStravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/auth': {
      id: '/api/strava/auth'
      path: '/api/strava/auth'
      fullPath: '/api/strava/auth'
      preLoaderRoute: typeof ApiStravaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GithubRoute: GithubRoute,
  HomeRoute: HomeRoute,
  StravaRoute: StravaRoute,
  ApiStravaAuthRoute: ApiStravaAuthRoute,
  ApiStravaCallbackRoute: ApiStravaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
